const DEVICES = [
  {id:'buttons',name:'A・Bボタン',icon:'🅰️',sca:'S',category:'sensor',builtIn:true,description:'押されたことを調べる',builtInNote:'本体表面のA・Bボタンを使います。外部のボタンは必要ありません。',targets:'ボタン 押す',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'基本',block:'ボタン A が押されたとき',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'Aボタンを押したら、ハートを表示してみよう。',ideas:['クイズの回答ボタン','ゲームのコントローラー'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/buttons/'},
  {id:'touch',name:'タッチロゴ',icon:'👆',sca:'S',category:'sensor',builtIn:true,description:'ロゴに触れたことを調べる',builtInNote:'本体表面の金色のロゴがタッチセンサです。外部センサは必要ありません。',targets:'触る タッチ',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'入力',block:'ロゴがタッチされたとき',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'ロゴに触れたら音を鳴らしてみよう。',ideas:['タッチ式スイッチ','びっくり箱'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/touch-logo/'},
  {id:'light',name:'明るさセンサ',icon:'☀️',sca:'S',category:'sensor',builtIn:true,description:'まわりの明るさを調べる',builtInNote:'LED画面が明るさを調べる役目もします。外部の明るさセンサは必要ありません。',targets:'明るさ 暗い 光',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'入力',block:'明るさ',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'暗くしたときの数字を表示してみよう。',ideas:['自動照明','朝を知らせる装置'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/light-sensing/'},
  {id:'temperature',name:'温度センサ',icon:'🌡️',sca:'S',category:'sensor',builtIn:true,description:'温度の変化を調べる',builtInNote:'本体の中で温度を調べられます。外部の温度センサは必要ありません。',targets:'温度 暑い 寒い',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'入力',block:'温度（℃）',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'今の温度をLEDに表示してみよう。',ideas:['暑さお知らせ装置','温度記録'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/temperature/'},
  {id:'microphone',name:'マイク',icon:'🎤',sca:'S',category:'sensor',builtIn:true,description:'音の大きさを調べる',builtInNote:'本体表面にマイクがあります。外部マイクは必要ありません。',targets:'音 拍手 声 大きい',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'入力',block:'音の大きさ',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'手をたたいたときの数字を表示してみよう。',ideas:['騒音お知らせ装置','拍手スイッチ'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/microphone/'},
  {id:'accelerometer',name:'加速度センサ',icon:'🫨',sca:'S',category:'sensor',builtIn:true,description:'傾きや揺れ、動きを調べる',builtInNote:'本体の中に動きを調べるセンサがあります。外部センサは必要ありません。',targets:'動き 揺れ 傾き',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'入力',block:'ゆさぶられたとき',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'micro:bitを振ったらマークを表示してみよう。',ideas:['転倒お知らせ','歩数カウンター'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/accelerometer/'},
  {id:'compass',name:'コンパス／磁気',icon:'🧭',sca:'S',category:'sensor',builtIn:true,description:'方角や磁石の近さを調べる',builtInNote:'本体の中に方角と磁気を調べるセンサがあります。外部コンパスは必要ありません。',targets:'方角 磁石 磁気',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'入力',block:'方角（°）',image:'assets/diagrams/microbit-v2-features.png',blockImage:'assets/makecode/input-builtins.png',firstTest:'北を向いたときにNを表示してみよう。',ideas:['宝探しコンパス','ドア開閉検知'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/compass/'},
  {id:'pir',name:'人感センサ HC-SR505',icon:'🚶',sca:'S',category:'sensor',description:'人などが動いたことを調べる',targets:'人 動き いる 防犯 ドア',connection:'micro:bitへ直接',shield:false,ports:['P0'],portsRequired:1,operation:'デジタル入力',block:'デジタル値を読み取る P0',path:'高度なブロック → 入出力端子',extension:'不要',image:'assets/devices/pir-hc-sr505.png',firstTest:'人を検知したらLEDにハートを表示してみよう。',ideas:['自動照明','防犯装置','自動ドア'],parts:['micro:bit','人感センサ HC-SR505','ワニ口クリップ'],source:'https://electronicwork.shop/items/624f0a36b34a5606a8ed57e6'},
  {id:'soil',name:'土壌水分センサ',icon:'🌱',sca:'S',category:'sensor',description:'土がどれくらい湿っているかを数字で調べる',targets:'土 水分 乾燥 植物 水やり',connection:'micro:bitへ直接',shield:false,ports:['P0'],portsRequired:1,operation:'アナログ入力',block:'アナログ値を読み取る P0',path:'高度なブロック → 入出力端子',extension:'不要',image:'assets/devices/soil-moisture.png',firstTest:'読み取った数字をLEDに表示してみよう。乾燥：約821、かなり湿った状態：約322は実測例。土やセンサで変わるので、自分で境目を決めよう。',ideas:['自動水やり装置','植物の乾燥アラーム'],parts:['micro:bit','土壌水分センサ','ワニ口クリップ'],source:'https://electronicwork.shop/items/63fe1ec334e0176fe906f6ac'},
  {id:'distance',name:'超音波距離センサ HC-SR04',icon:'📏',sca:'S',category:'sensor',description:'物まで何cmあるかを調べる',targets:'距離 近い cm ドア',connection:'micro:bitへ直接',shield:false,ports:['P0','P1'],portRoles:['Trig','Echo'],portsRequired:2,operation:'距離',block:'ping（cm）',extension:'Sonar',image:'assets/devices/hc-sr04.jpg',firstTest:'測った距離をcmでLEDに表示してみよう。',ideas:['近づくと開くドア','満杯お知らせ','距離計'],parts:['micro:bit','HC-SR04 超音波距離センサ','ワニ口クリップ'],source:'https://www.sparkfun.com/products/15569'},
  {id:'scale',name:'重量センサ',icon:'⚖️',sca:'S',category:'sensor',description:'上に置いたものが何gあるか調べる',targets:'重さ 重量 g 空 容器 水皿 M5Stack Unit Mini Scales',connection:'Grove接続（I2C）',shield:true,ports:[],operation:'重さ',block:'重量センサの重さ（整数g）',extension:'野田中オリジナル拡張機能',extensionUrl:'https://github.com/playa2021git/pxt-mini-scales',image:'assets/devices/mini-scales.webp',firstTest:'容器を置いて風袋引きし、重さをgで表示してみよう。風袋引きは、容器を置いた状態を0gにすること。',ideas:['水皿の空検知','残量お知らせ','簡単なはかり'],parts:['micro:bit','Grove Shield','重量センサ'],source:'https://docs.m5stack.com/en/unit/Unit-Mini%20Scales'},
  {id:'led',name:'5×5 LED',icon:'💡',sca:'A',category:'actuator',builtIn:true,description:'数字・文字・マーク・光で知らせる',builtInNote:'本体表面の25個のLEDを使います。外部LEDは必要ありません。',targets:'光る 表示 数字 文字',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'基本',block:'LED画面に表示',image:'assets/diagrams/microbit-v2-features.png',firstTest:'ハートのマークを表示してみよう。',ideas:['メッセージ表示','警告ランプ'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/leds-and-buttons/'},
  {id:'speaker',name:'スピーカー',icon:'🔊',sca:'A',category:'actuator',builtIn:true,description:'音で知らせる',builtInNote:'本体の裏側にスピーカーがあります。外部スピーカーは必要ありません。',targets:'音 音楽 鳴る 知らせる',connection:'micro:bitに内蔵',shield:false,ports:[],operation:'音楽',block:'メロディを開始する',image:'assets/diagrams/microbit-v2-features.png',firstTest:'Aボタンを押したら音を鳴らしてみよう。',ideas:['アラーム','楽器'],parts:['micro:bit'],source:'https://microbit.org/get-started/features/speaker/'},
  {id:'servo',name:'180°サーボモータ（SG90）',icon:'↪️',sca:'A',category:'actuator',description:'決めた角度まで動かせるモータ',targets:'動く 角度 ドア 開ける SG90',connection:'micro:bitへ直接',shield:false,ports:['P0'],portsRequired:1,operation:'角度',block:'サーボ P0 の角度を 90° にする',extension:'Servo',image:'assets/devices/servo-sg90.png',firstTest:'Aボタンを押したら90°へ動かしてみよう。',ideas:['自動ドア','ペットのえさやり','動く案内板'],parts:['micro:bit','180°サーボモータ SG90','ワニ口クリップ'],source:'https://maisonup.in/products/sg90-micro-servo-motor'},
  {id:'vibrator',name:'振動モータ',icon:'📳',sca:'A',category:'actuator',description:'振動の強さを変えて、ブルブル震えて知らせる',targets:'振動 震える 強さ PWM アナログ 知らせる M5Stack Vibrator Unit',connection:'Grove接続',shield:true,ports:['P0'],portsRequired:1,operation:'アナログ出力',block:'アナログで出力する P0 値 0〜1023',path:'高度なブロック → 入出力端子',extension:'不要',image:'assets/devices/vibrator.webp',firstTest:'Aボタンを押したら小さく振動、Bボタンを押したら強く振動させ、強さの違いを確かめよう。値を大きくすると振動も強くなります。',ideas:['静かなお知らせ','ゲームの振動'],parts:['micro:bit','Grove Shield','振動モータ'],source:'https://docs.m5stack.com/en/unit/vibrator'},
  {id:'pump',name:'デジタルマイクロポンプ',icon:'💧',sca:'A',category:'actuator',description:'水や空気を送る',targets:'水 空気 ポンプ 水やり',connection:'Grove接続',shield:true,ports:[],operation:'デジタル出力',block:'1 → ポンプON ／ 0 → ポンプOFF',extension:'不要',image:'assets/devices/digital-pump.png',firstTest:'Aボタンで短時間だけ動かそう。ポンプON → 少し待つ → ポンプOFFの順にします。',ideas:['自動水やり装置','水皿の補給'],parts:['micro:bit','Grove Shield','デジタルマイクロポンプ'],source:'https://shop.tfabworks.com/products/tfw-ad-pp2'},
  {id:'ai-image',name:'AI画像認識',icon:'📷',sca:'AI',category:'ai',description:'カメラで物や人を見分ける',targets:'AI 猫 人 画像 ペットボトル 水皿',connection:'Teachable Machineと連携',shield:false,ports:[],operation:'AI',block:'認識した結果を使う',extension:'連携方法を選ぶ',image:'assets/devices/ai-image-learning.png',firstTest:'2種類の物を学習させ、認識結果を画面に表示してみよう。',ideas:['猫が来たら知らせる','ごみ分別サポート'],parts:['パソコンのカメラ','Teachable Machine','micro:bit（実物を動かす場合）'],source:'https://teachablemachine.withgoogle.com/'},
  {id:'ai-sound',name:'AI音認識',icon:'🎙️',sca:'AI',category:'ai',description:'拍手や声などの音を見分ける',targets:'AI 音 拍手 声',connection:'Teachable Machineと連携',shield:false,ports:[],operation:'AI',block:'認識した結果を使う',extension:'連携方法を選ぶ',image:'assets/devices/ai-sound-learning.png',firstTest:'拍手と周りの音を学習させ、結果を表示してみよう。',ideas:['拍手で動く装置','音の種類で変わるライト'],parts:['パソコンのマイク','Teachable Machine','micro:bit（実物を動かす場合）'],source:'https://teachablemachine.withgoogle.com/'},
  {id:'ai-pose',name:'AIポーズ認識',icon:'🧍',sca:'AI',category:'ai',description:'体のポーズを見分ける',targets:'AI ポーズ 手 立つ しゃがむ',connection:'Teachable Machineと連携',shield:false,ports:[],operation:'AI',block:'認識した結果を使う',extension:'連携方法を選ぶ',image:'assets/devices/ai-pose-learning.png',firstTest:'手を上げる／下げるを学習させ、結果を表示してみよう。',ideas:['ポーズで開くドア','体操チェック'],parts:['パソコンのカメラ','Teachable Machine','micro:bit（実物を動かす場合）'],source:'https://teachablemachine.withgoogle.com/'}
];

const FILTERS = [
  ['all','すべて'],['sensor','👀 S センサ'],['actuator','⚙️ A 動かす'],['built-in','✅ micro:bit内蔵'],['direct','🐊 直接接続'],['grove','🔌 Grove接続'],['shield-no','Shield不要'],['shield-yes','Shield必要'],['extension-no','拡張機能不要'],['extension-yes','拡張機能必要'],['ai','🤖 AI']
];
